CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200418235006_Add customer entity') THEN
    CREATE TABLE "Customers" (
        "CustomerId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "Address" text NULL,
        "AttentionOrCareOf" text NULL,
        "Suite" text NULL,
        "City" text NULL,
        "State" text NULL,
        "ZipCode" text NULL,
        "BillingContact" text NULL,
        "PhoneNumber" text NULL,
        "SalesPerson" text NULL,
        "BalanceMethod" text NULL,
        "TermsCode" text NULL,
        "CreditLimit" text NULL,
        "AverageDaysToPay" text NULL,
        "AverageDaysToPays" numeric NOT NULL,
        "CurrentBalance" numeric NOT NULL,
        "PastDueAmount" numeric NOT NULL,
        "HighBalance" numeric NOT NULL,
        "Pricing" numeric NOT NULL,
        "Discount" numeric NOT NULL,
        "RequiredPoNumber" integer NOT NULL,
        "ShipVia" text NULL,
        "TaxCode" text NULL,
        "ShipTo" text NULL,
        "BillTo" text NULL,
        "Type" text NULL,
        "Group" text NULL,
        "TaxNumber" integer NOT NULL,
        "AccountReceivable" integer NOT NULL,
        "User" text NULL,
        "SalesPtdHistory" numeric NOT NULL,
        "SalesYtdHistory" numeric NOT NULL,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("CustomerId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200418235006_Add customer entity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200418235006_Add customer entity', '3.1.0');
    END IF;
END $$;
