// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TPS.Data;

namespace TPS.Migrations.TpsDb
{
    [DbContext(typeof(TpsDbContext))]
    [Migration("20200503154313_Changed decimal and int to nullable on Customer table and removed duplicate column.v2")]
    partial class ChangeddecimalandinttonullableonCustomertableandremovedduplicatecolumnv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TPS.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AccountReceivable")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AttentionOrCareOf")
                        .HasColumnType("text");

                    b.Property<string>("BalanceMethod")
                        .HasColumnType("text");

                    b.Property<string>("BillTo")
                        .HasColumnType("text");

                    b.Property<string>("BillingContact")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CreditLimit")
                        .HasColumnType("text");

                    b.Property<decimal?>("CurrentBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric");

                    b.Property<string>("Group")
                        .HasColumnType("text");

                    b.Property<decimal?>("HighBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal?>("PastDueAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("Pricing")
                        .HasColumnType("numeric");

                    b.Property<int?>("RequiredPoNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SalesPerson")
                        .HasColumnType("text");

                    b.Property<decimal?>("SalesPtdHistory")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalesYtdHistory")
                        .HasColumnType("numeric");

                    b.Property<string>("ShipTo")
                        .HasColumnType("text");

                    b.Property<string>("ShipVia")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Suite")
                        .HasColumnType("text");

                    b.Property<string>("TaxCode")
                        .HasColumnType("text");

                    b.Property<int?>("TaxNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TermsCode")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers","CustomerManagement");
                });
#pragma warning restore 612, 618
        }
    }
}
